### ISSUE TITLE
Naming of author

### ISSUE THREAD

**Issue by drgrigg** [animeshbaranawal/Book48511#1]
Lint throws up a number of problems, but the following should fix most of them.

One major issue: it's not our practice to include the "Sir" as part of the author's name (see, for example, our books by Sir Arthur Conan Doyle). You would need to change this in several places in your repository. The best way to deal with this (and the lint issues to do with mismatches with our template files) would be:

1) Make sure you're running the latest version of our toolset

2) In a new folder, re-run se create-draft with a command-line like: 

` se create-draft -a="Richard Francis Burton" -t="Vikram and the Vampire"`

3) From this new (dummy) folder, copy these files into your current repository folder, overwriting your current ones:

LICENSE.md
images/cover.svg
images/titlepage.svg
src/epub/css/se.css
src/epub/images/logo.svg
src/epub/text/uncopyright.xhtml

4) Re-run `se build-images .`

5) Manually edit src/epub/text/titlepage.xhtml, colophon.xhtml and imprint to remove the 'Sir' as appropriate.

6) Do the same carefully in content.opf, both in SE urls and in the meta data of the author's name. You might note that even Wikipedia's canonical link for this person doesn't use the Sir, though the version you have is redirected to it.

7) While you're in content.opf, add the roles to the author which lint complains are missing.

I think that's all for the moment.

**Comment by animeshbaranawal** [comment]
This issue has been addressed as part of the three successive commits: 1e35c594 - a8eaeb80

**Comment by animeshbaranawal** [comment]
NOTE: The main branch has been rebased.
This issue has been addressed as part of the three successive commits: 484fc755 - 0ce4a88b
