### ISSUE TITLE
CSS class p.noindent is not needed and should be removed

### ISSUE THREAD

**Issue by drgrigg** [animeshbaranawal/Book48511#10]
Our normal CSS will do what is required with indentation. You should remove `p.noindent` from local.css and in all instances where it has been used.

Also, it's not our style to put the first word or word of a chapter in small-caps as you've done with `<b>` tags. You should remove those too.

**Comment by animeshbaranawal** [comment]
Fixed as part of commit 3d971e18

**Comment by animeshbaranawal** [comment]
NOTE: The main branch has been rebased.
This issue has been addressed as part of 44ff6d1
