### ISSUE TITLE
Your name in colophon should be tagged

### ISSUE THREAD

**Issue by drgrigg** [animeshbaranawal/Book48511#11]
Your own name should be treated in the same way as those of the transcribers by placing it within a semanticated `<b>` tag unless you want to hyperlink it somewhere, in which case it should of course be in an `<a>` tag.

**Comment by drgrigg** [comment]
I mean it should look like:

`<b epub:type="z3998:personal-name">Animesh Baranawal</b>,`

**Comment by animeshbaranawal** [comment]
Fixed as part of commit 2ad9b1a1

**Comment by animeshbaranawal** [comment]
NOTE: The main branch has been rebased.
This issue has been addressed as part of f4a8492
