### ISSUE TITLE
Not really an issue, just a comment on word count

### ISSUE THREAD

**Issue by drgrigg** [animeshbaranawal/Book48511#12]
Regarding commit 7d5d844 .

 You don't need to fiddle with the word count in content.opf. Indeed, you should leave it as the placeholder WORD_COUNT, similarly with READING_EASE. These are set with the `se prepare-release` function, but that's something which **Alex** does just before release.

**Comment by animeshbaranawal** [comment]
Fixed as part of commit 19dbe24c

**Comment by animeshbaranawal** [comment]
NOTE: The main branch has been rebased.
This issue has been addressed as part of df7a789
