### ISSUE TITLE
Typogrify makes a few changes which should be accepted

### ISSUE THREAD

**Issue by drgrigg** [animeshbaranawal/Book48511#13]
If you run typogrify again it makes a total of five changes, all of which I think you should allow.  Mostly these are instances of commas preceding dashes.

**Comment by animeshbaranawal** [comment]
I think there should be two exceptions to the changes made by `se typogrify`:
1. Chapter 1 : line 21 - the em-dashes for the stretched word "modesty" are changed as rightly pointed in the manual section 8.7.7.6
2. Chapter 1 : line 25 - the word "modesty" is obscured and double em-dash is used as mentioned in the manual section 8.7.7.8.4

Punctuation changes are fixed as part of commit 560338f

**Comment by drgrigg** [comment]
Yes, thanks, you are right.
