### ISSUE TITLE
Dedication styling makes it very small 

### ISSUE THREAD

**Issue by drgrigg** [animeshbaranawal/Book48511#14]
I don't think you should set the default size of the paragraphs to be x-small. The whole thing looks tiny now, see the screenshot below from Apple Books. Even the first line is a bit small. Maybe use sizes specified in ems?

![Screenshot 2022-06-08 14-42-03](https://user-images.githubusercontent.com/7020970/172533396-dfc6e37a-eaa7-4bb3-984f-5b8512ca07a1.jpg)

**Comment by animeshbaranawal** [comment]
Fixed as part of commit cfa58bb, df1fa76
