### ISSUE TITLE
Lint issues remain

### ISSUE THREAD

**Issue by drgrigg** [animeshbaranawal/Book48511#2]
I'm still seeing issues when I run lint.  Let's look at these one by one:

`s-060 | Manual Review | endnotes.xhtml | Italics on name that requires quotes`. This is just a stylistic decision on our part, which should probably be covered in the manual, but as yet I don't think it is (I'll fix that). Song titles, short stories and essays don't get italics, but are quoted, eg "Essay on Vikram". You could if you like leave a span containing the semantic information, eg:

`“<span epub:type="se:name.publication.essay">Essay on Vikram</span>”`

**Comment by drgrigg** [comment]
`t-070 | Manual Review | epigraph.xhtml | <cite> in epigraph ending in a period.` This should be self-explanatory, just take the period of the the <cite> and put it outside the tags.

**Comment by drgrigg** [comment]
`s-036 │ Manual Review │ introduction.xhtml │ No frontmatter semantic inflection for what looks like a frontmatter file.` This is because you have given the introduction the epub:type of "bodymatter". Generally we give introductions the type of "frontmatter" and place them before the halftitle page. However, in this case, you could definitely argue that it really is part of the body of the work, as indicated by its placement in the content page of the scans.

This is therefore a candidate for inclusion in an se-lint-ignore.xml file so it doesn't keep getting flagged. See t[his part of the manual](https://standardebooks.org/manual/1.6.4/2-filesystem#2.3) about how to put that together.

**Comment by drgrigg** [comment]
`c-008 │ Manual Review │ local.css│ CSS class only used once. Can a clever selector be crafted instead of a single-use class? When possible classes should not be single-use style hooks.`

The problem here is the dedication. You are using h1, h2, h3 tags to format the dedication. That's incorrect. Those heading levels have semantic meaning and shouldn't be used for styling. You can replace them with CSS which specifically targets the dedication. I would use paragraphs instead of `<br/>` tags. You can then target specific paragraphs in the CSS.

**Comment by drgrigg** [comment]
Once you have fixed the dedication, could you run `se build-toc` again? There may be a bug in that code which I'd like to check. If it crashes, please let me know.

However if it runs OK and makes changes, you should accept those. In my testing it removes a couple of items in the Landmarks section of the ToC, which is a new change to our standard.

**Comment by animeshbaranawal** [comment]
se build-toc works fine. Changes to toc.html have been pushed as part of commit e75b4f9c

I am struggling with the dedication segment.
I am able to fix the warnings using proper semantic inflection classes using \<span\> and \<br/\>.
Replacing them with \<p\> gives an issue. The .xhtml rendering on my browser works fine but when I build the .epub file and view it, the rendering does not work. I am using Foliate to view it on my Linux desktop. Maybe an issue with the application itself. I will also try it to view on my IPad.

**Comment by drgrigg** [comment]
Can you share the CSS you're trying to use? It should just be a matter of specifying the particular paragraphs using `p:nth-of-type`.

**Comment by animeshbaranawal** [comment]
Seems the issue is with the Foliate app renderer. The new CSS works fine on my IPad.
Fixed as part of commit c609d13

**Comment by animeshbaranawal** [comment]
NOTE: The main branch has been rebased.
The issue is fixed as part of commits bf236cf, 06c8fb1.
