### ISSUE TITLE
Query on phrase possibly requiring language tag?

### ISSUE THREAD

**Issue by drgrigg** [animeshbaranawal/Book48511#5]
In the preface, we have:

` which Apuleius calls ‘Milesius sermo,’`

Is the quoted phrase Latin? If so, I think it needs to be italicised not quoted and given the appropriate language tag.

**Comment by animeshbaranawal** [comment]
https://ancientnarrative.com/article/view/24429/21879
It seems Milesius sermo is a latin text.
Should I let this be in quotes or italicise it with the proper epub:type?

**Comment by drgrigg** [comment]
I would italicise it with both xml:lang=“la” and epub:type=“se:name.publication.book” in the `<i>` tag. And remove the quotes.

**Comment by drgrigg** [comment]
That **doesn’t** need to be an Editorial commit, by the way.

**Comment by animeshbaranawal** [comment]
Fixed as part of commit 3f5ecb0f.

**Comment by animeshbaranawal** [comment]
NOTE: The main branch has been rebased.
This issue has been addressed as part of 8852cbc
