### ISSUE TITLE
Unnecessary quotes or italics

### ISSUE THREAD

**Issue by drgrigg** [animeshbaranawal/Book48511#6]
In instances like these in chapters 1 and 7:

`“<i>ughs</i>” and “<i>poohs</i>,”`

I would suggest it would be best to drop either the italics or the quotes, rather than using both, regardless of what the page scans show. I would probably drop the italics.

**Comment by drgrigg** [comment]
In the endnotes, you have a number of instances of `<em>` tags which ought to be italics with the appropriate language tags. Eg: note 165:

`This is <em>prévoyance</em> on the part of the Vampire`

Should be `<i xml:lang="fr">` rather than `<em>`.

Similarly in the preface:

`<em>gouaches</em>`

And I also think here: 

`an older book, the <i epub:type="se:name.publication.book">Panchatantra</i>, or <em>Five Chapters</em>`

The Five Chapters should also be italicised and semanticated as a book.

**Comment by animeshbaranawal** [comment]
preface - line 35: Should Ten Days be italicised as well? 
It is not italicised in the scan but it is a title translation of the book Decamerone.

**Comment by animeshbaranawal** [comment]
Ignore the last two commit references. I have reworded these commits to address to #7 .

**Comment by drgrigg** [comment]
> preface - line 35: Should Ten Days be italicised as well?
> It is not italicised in the scan but it is a title translation of the book Decamerone.

Yes, I would do so.

**Comment by drgrigg** [comment]
My mistake here: "gouaches" in the Preface should have the italics removed entirely (our rule is that if a foreign word is in the Merriam-Webster dictionary it should generally not be italicised).

**Comment by animeshbaranawal** [comment]
Fixed as part of commit d56e17ae

**Comment by animeshbaranawal** [comment]
NOTE: The main branch has been rebased.
This issue has been addressed as part of 4620c30, 946f9a7
