### ISSUE TITLE
Modernize-spelling makes changes which should be accepted

### ISSUE THREAD

**Issue by drgrigg** [animeshbaranawal/Book48511#7]
Running `se modernize-spelling` results in a number of changes which should be accepted. Make sure to commit these with a message starting with "[Editorial]".

You seem to have gone backwards and forwards a few times with the spelling of Brahma. I think "Bramha" is surely a mistake on Burton's part and could be corrected in an "[Editorial]" commit. Do you have a view on this? Is there a reason you reverted to "Bramha"?

Note that there are problems with a number of your existing commits which are marked as "[Editorial]", some of which shouldn't be. I'll address these in a separate issue.

**Comment by animeshbaranawal** [comment]
I refrained from changing any spelling at all unless they were obvious typos like in names. 
Later, when I proofread against a second edited version of the work (https://archive.org/details/vikramvampireort1893burt), the typos on the word "Bramha" were fixed.

I am sorry about the issues in existing commits regarding the "Editorial" tag.
Moving forward, I will be annotating the commits as accurately as possible.

**Comment by drgrigg** [comment]
No need to apologise about the wrong use of [Editorial]. We need to clarify this in the manual, something I’ll get to shortly.

**Comment by drgrigg** [comment]
There's one change which modernize-spelling made which should be reverted, in the conclusion.

`Prosperity to thine and thy son’s forever and ever`

I believe that shouldn't have changed and should be be reverted to `for ever and ever`.

**Comment by animeshbaranawal** [comment]
I am at a fence for this: https://www.grammarphobia.com/blog/2012/02/forever.html
I think we should keep it as "forever" or "for ever" at all the changes since the meaning used in all contexts is the same: "eternal".

Also, I noticed that there are words like "civilised" which have different american spelling variant "civilized".
Should these be changed or left as is?

**Comment by drgrigg** [comment]
I think you are correct (and thus, I am wrong!) about "forever and ever". Leave it like that, and leave all of the other "forever"s as one word. This means, by the way, that I've been wrong on some of my own productions and will now need to go back and fix those :-(  

Your second point raises an issue which I should have spotted before but didn't. All of the language in Burton's text is British English, not American English. You can tell this by doing a search for words like "honour" and "colour" and as you point out, "civilised".

This means that you need to change the en-US tags at the head of the body text files to en-GB. By "body text" I mean the chapters, the introduction, preface, etc which are part of Burton's text. 

**Don't change** the tags in SE template files like uncopyright.xhtml, imprint.xhtml and colophon.xhtml. **Do** also change it here `<dc:language>en-US</dc:language>` in content.opf.

**Comment by animeshbaranawal** [comment]
Language metatag changed as part of commit e6e5bc8d

**Comment by animeshbaranawal** [comment]
NOTE: The main branch has been rebased.
This issue has been addressed as part of 15120c8, 48957d0

**Comment by drgrigg** [comment]
One last thing, running lint shows that I should have told you to also change the language tag from en-US to en-GB in halftitlepage.xhtml. That's the only lint error now.

**Comment by animeshbaranawal** [comment]
On my machine, se lint does not throw any error. I am using version 2.3.10 on Ubuntu 20.04. Anyways, I have made the changes for consistency reasons as part of commit 71b723ed
