### ISSUE TITLE
Mistaken use of [Editorial] in some commit messages

### ISSUE THREAD

**Issue by drgrigg** [animeshbaranawal/Book48511#8]
This is a big issue, I'm afraid.

A number of your commits marked as [Editorial] don't appear as though they are Editorial changes by our standards, rather they are corrections or adjustments to formatting. We reserve the [Editorial] flag for commits _which change the text away from what is shown by the page scans_ (eg what happens during the `se modernize-spelling` process). Changes to formatting, the correction of typos, etc, don't fall into that category. We only want to mark changes with [Editorial] if they represent an editorial decision to deviate from the page scans.

Also, there are many commits which seem to **combine** an editorial commit with other actions, which isn't acceptable. However, because most of these seem to be to do with changing or reverting the spelling of Brahma and the change from O to O', which were ultimately reverted, I **think** it would be OK to just remove the [Editorial] marking from those messages. 

However, **before you take any action on this issue**, we'll need to ask Alex @acabal to comment on whether he agrees this is a reasonable approach.

For your and Alex's reference, these are the commits which in my view should have the [Editorial] removed using an interactive rebase:

eda01bc: Finalise changes to conclusion [Editorial] Revert changes to (Bramha,Brahma)
40e25af: Finalise changes to chapter 11 [Editorial] revert changes like (O,O')
271bff7: Finalise changes to chapter 10 [Editorial] Revert changes like (O,O') and (Brahma,Bramha)
143f498: Finalise changes to chapter 8 [Editorial] Revert changes to spelling (Brahma, Bramha).
bbddd6f: Finalised changes to chapter 6. [Editorial] Reverted changes on spellings (Brahma, Bramha).
626d9de: Finalised changes to introduction [Editorial] Revert spelling changes (Brahma,Bramha)
e69e745: Typogrify changes to Conclusion [Editorial] Bramha -> Brahma
9df726a: Typogrify chanes to chapter 10. [Editorial] Bramha -> Brahma, O -> O'
d96e845: Typogrify changes to Chapter8 [Editorial] Murdev -> Muldev, Bramha->Brahma

In the last one, it looks as though Murdev was a typo for Muldev, so it didn't need to be [Editorial].

The following early commits seem to be just normal proof-reading/formatting, and should definitely have [Editorial] removed.

9486d20: [Editorial] Pass through Introduction completed. Some typogrify changes to Preface.
36c51fe: [Editorial] Pass through Preface completed.

**Comment by acabal** [comment]
Yes, that will need to be corrected. You can simply do an interactive rebase to reword those commit messages to remove [Editorial] from all of them. Not as hard as it sounds.

**Comment by drgrigg** [comment]
OK, please let me know if you need any help with the git rebase process.

**Comment by animeshbaranawal** [comment]
The branch has now been successfully rebased with the appropriate usage of [Editorial] tags.
Instead of doing an interactive rebase, I replayed all commits splitting the commits in case editorial actions were combined with other actions. Please let me know if there are issues remaining.
